# Generated by Django 5.0.6 on 2025-05-23 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_thread_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='author',
            field=models.CharField(max_length=255),
        ),
    ]
