# Generated by Django 4.2.5 on 2025-05-25 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_topbook'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TopBook',
        ),
    ]
