# Generated by Django 4.2.5 on 2025-05-26 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_community'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='category',
            field=models.CharField(choices=[('chat', '잡담'), ('share', '나눔'), ('reading', '읽는 중'), ('finished', '읽은 후')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='community',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
