# Generated by Django 4.2.5 on 2025-05-26 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_community_category_community_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='category',
            field=models.CharField(choices=[('chat', '잡담'), ('share', '나눔'), ('reading', '읽는 중'), ('finished', '읽은 후')], default='chat', max_length=10),
        ),
    ]
