# Generated by Django 4.2.5 on 2025-05-26 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0014_alter_community_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
    ]
