# Generated by Django 4.2.5 on 2025-05-26 03:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0015_community_is_popular'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='views',
        ),
        migrations.AddField(
            model_name='community',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_community_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
