# Generated by Django 4.2.5 on 2025-05-26 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0016_remove_community_views_community_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='is_popular',
        ),
    ]
