# Generated by Django 4.2.5 on 2025-05-26 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0018_communitycomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
