# Generated by Django 4.2.5 on 2025-05-26 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_topbook'),
        ('books', '0019_community_views'),
    ]

    operations = [
    ]
