# Generated by Django 4.2.5 on 2025-05-27 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0023_aireport_report_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aireport',
            name='report_image',
        ),
    ]
