# Generated by Django 4.2.5 on 2025-05-27 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0024_remove_aireport_report_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='aireport',
            name='report_image',
            field=models.ImageField(blank=True, null=True, upload_to='ai_reports/images/'),
        ),
    ]
